services:

  db:
    image: postgres:16
    container_name: task-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: task-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  tempo:
    image: grafana/tempo:latest
    container_name: task-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

  grafana:
    image: grafana/grafana:11.0.0
    container_name: task-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - tempo

  migrations:
    build:
      context: .
      dockerfile: TaskManagement.Api/Dockerfile.migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__Default: Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres

  api:
    build:
      context: .
      dockerfile: TaskManagement.Api/Dockerfile
    restart: unless-stopped
    depends_on:
      migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__Default: Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres
      RabbitMq__Host: rabbitmq
      RabbitMq__User: guest
      RabbitMq__Password: guest
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: TaskManagement.Api
      ASPNETCORE_ENVIRONMENT: Development

  consumer:
    build:
      context: .
      dockerfile: TaskManagement.Consumer/Dockerfile
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RabbitMq__Host: rabbitmq
      RabbitMq__User: guest
      RabbitMq__Password: guest
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: TaskManagement.Consumer

volumes:
  db_data:
